from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
answers = {
1: ("Retenir un avis obligatoire avant les lois, budgets et plans à effets durables, accompagné d'une réponse publique du Parlement ou du gouvernement avant adoption. L'avis expose les dommages différés et les alternatives ; il ne crée pas de veto scientifique. L'absence de réponse peut être contestée devant le juge compétent.", "Un effet suspensif général donnerait un pouvoir de blocage trop large à l'expertise. Réviser le dispositif si les réponses deviennent formelles ou arrivent après les décisions irréversibles."),
2: ("Retenir une demande motivée par une assemblée citoyenne représentative, adoptée aux trois cinquièmes de ses membres. Les citoyens peuvent saisir ce panel par une pétition ou un signalement documenté, sans seuil conditionnant les recours individuels. L'autorité visée répond sous soixante jours, en annonçant les corrections ou les raisons du maintien.", "Le seuil et le délai sont des paramètres d'essai : le premier recherche un accord dépassant une majorité étroite, le second limite l'attente. Réviser s'ils bloquent les alertes minoritaires ou saturent l'instruction ; une atteinte urgente aux droits relève directement du juge."),
3: ("Réouvrir l'arbitrage sur les moyens, le calendrier et les compensations, avec plusieurs trajectoires compatibles. Deux modèles validés peuvent servir des priorités sociales différentes : les représentants, éclairés par la délibération citoyenne, choisissent et motivent ce choix. Le consortium doit distinguer impossibilité physique, incertitude et préférence de valeur.", "Une validation technique ne suffit pas à imposer la trajectoire rejetée. Pendant le réexamen, maintenir les protections existantes ; si aucune trajectoire n'est réalisable, documenter l'incompatibilité et revoir les moyens. La procédure d'urgence ne s'applique qu'en présence de ses propres critères."),
4: ("Confier l'appel à une formation spécialisée d'une juridiction indépendante, en privilégiant les juridictions existantes. Elle peut ordonner une contre-expertise, suspendre les effets du classement et imposer une nouvelle instruction ; elle contrôle les droits, la procédure et les motifs sans décréter une vérité scientifique. Le recours est ouvert aux personnes et organisations affectées, pas seulement aux partis.", "Un second collège scientifique seul ne protège pas suffisamment les droits. Prévoir une voie urgente en cas de dommage grave et publier les délais ; renforcer les moyens si le coût ou l'attente rendent le recours inaccessible."),
5: ("Exiger conjointement une dépendance importante à une expertise spécialisée, un risque grave ou systémique documenté et l'insuffisance des procédures ordinaires. Le Parlement délimite par la loi les seuls paramètres techniques concernés, après expertise contradictoire et audit. Le mandat précise durée, budget, recours et décisions de valeur qui restent démocratiques.", "Une inscription décidée par le consortium lui-même favoriserait l'extension de son pouvoir. Réviser ou réduire le périmètre si des préférences politiques y sont traitées comme des contraintes scientifiques."),
6: ("Retenir un réexamen tous les quatre ans. Le gouvernement justifie le maintien devant le Parlement sur la base d'une évaluation indépendante des risques, coûts et effets sur les droits. Faute de renouvellement motivé, la compétence renforcée expire ; les normes de sûreté, obligations ordinaires et recours restent applicables.", "Le consortium peut être entendu mais ne possède pas de veto sur sa propre compétence. Adapter cette périodicité d'essai si elle produit une instabilité préjudiciable ou laisse perdurer un dispositif sans utilité démontrée."),
7: ("L'exécutif doit documenter un danger grave et imminent pour une fonction vitale, l'insuffisance des pouvoirs ordinaires et la nécessité de chaque mesure exceptionnelle. Les seuils sectoriels combinent gravité, population exposée, capacité restante et délai avant dommage ; ils sont publiés à l'avance. Un indice global ne déclenche pas automatiquement des restrictions.", "Prévoir une confirmation parlementaire sous sept jours, avec recours judiciaire immédiat et motivation publique des données manquantes. Ce délai est une hypothèse de conception. L'alerte et la mobilisation des secours ordinaires n'attendent pas une déclaration d'urgence."),
8: ("Retenir trente jours au maximum pour une mesure exceptionnelle confirmée par le Parlement, avec une durée plus courte lorsque le besoin le permet. Sans confirmation sous sept jours, les pouvoirs exceptionnels expirent. Toute prolongation exige un vote, un bilan public et une nouvelle date de fin ; le suivi de nécessité est hebdomadaire.", "Sept et trente jours sont des plafonds provisoires proposés, pas des délais juridiques existants. Vérifier leur compatibilité locale avant application. Réviser si les renouvellements deviennent automatiques ; maintenir les secours ordinaires et les droits non dérogeables."),
9: ("Donner à l'autorité d'audit accès aux pièces nécessaires, pouvoir de publication et d'injonction corrective avec délai et recours. En cas de défaut grave, elle saisit le juge pour une suspension ou une sanction ; l'administration peut arrêter volontairement l'usage du modèle et activer un fonctionnement de secours. La saisine ne suspend pas automatiquement l'accès au socle.", "L'audit exclusivement consultatif serait trop faible ; le cumul de l'enquête et des sanctions définitives concentrerait le pouvoir. Mesurer les corrections effectives, les délais et les décisions annulées ; réviser si l'injonction devient un moyen de diriger les politiques."),
10: ("Confier l'audit initial à un service juridique indépendant auprès du Parlement, avec expertise territoriale et contradictoire. Pour chaque mesure, publier norme concernée, autorité compétente, droits affectés, voie d'adoption et classement : compatible, adaptable, incompatible en l'état, ou impossible sans modification d'une norme supérieure. Le juge conserve le contrôle final.", "L'audit scientifique ne remplace pas l'analyse juridique. Une institution pilote reste dans les pouvoirs que le droit lui donne déjà ; une incompatibilité entraîne adaptation, procédure légale de réforme ou abandon. Réviser le service si sa dépendance politique ou ses délais bloquent l'examen loyal."),
11: ("Retenir un tirage au sort en deux étapes : invitations aléatoires, puis sélection stratifiée parmi les personnes acceptant librement. Corriger la non-réponse par des invitations supplémentaires et des moyens d'accès : indemnisation, transport, garde, handicap, traduction et formats oraux. Les experts et intérêts organisés sont auditionnés sans voter dans le panel.", "Le volontariat seul peut surreprésenter les personnes disponibles. Publier la méthode et les écarts de composition sans données personnelles identifiantes. Réviser le recrutement si des groupes restent absents ; le panel ne se substitue ni au suffrage ni aux recours."),
12: ("Réserver le référendum aux choix de valeurs et de trajectoires compatibles, lorsque le droit du territoire le permet. Exiger une question claire, une information contradictoire, la transparence des campagnes et un contrôle préalable contestable des droits et contraintes invoquées. Une incertitude scientifique doit apparaître comme telle dans le dossier.", "Ni une majorité ni un consortium ne peuvent retirer arbitrairement les droits d'un groupe. L'appel décrit en réponse 4 protège contre un filtrage politique. Réviser les modalités si le cadrage de la question ou les financements empêchent un choix éclairé."),
13: ("Publier un dossier à deux niveaux : une synthèse accessible présentant options, effets et désaccords, puis les données et méthodes détaillées. Une équipe éditoriale indépendante de l'exécutif, recrutée avec les garanties de l'audit, prépare le dossier ; un panel de lecteurs vérifie sa compréhension. Les parties entendues disposent d'un droit de rectification et leurs financements sont visibles.", "Une brochure gouvernementale seule expose à la propagande ; une juxtaposition de contributions ne garantit pas la compréhension. Réviser lorsque les tests de lecture révèlent des contresens ou que des critiques documentées sont écartées. Une hypothèse faible n'obtient pas artificiellement le poids d'un résultat robuste."),
14: ("Combiner contributions ouvertes, recrutement aléatoire stratifié et participation hors ligne. Définir avant la consultation la population visée et les écarts de composition acceptables ; publier participation, non-réponse et limites des éventuelles pondérations. Une consultation volontaire ou un panel délibératif ne mesure pas automatiquement l'opinion de toute la population.", "Un nombre minimal de clics ne démontre aucune représentativité. Si un groupe pertinent manque ou si les données ne permettent pas l'inférence, présenter les résultats comme exploratoires et compléter le recrutement. Réviser la méthode plutôt que collecter des profils individuels toujours plus détaillés."),
15: ("Retenir une évaluation annuelle légère et une décision de renouvellement tous les quatre ans. Examiner les réponses reçues, modifications réellement obtenues, groupes inclus, coût et compréhension. Un mécanisme expérimental sans effet démontrable expire ou est remplacé ; les droits de participation et de recours continuent par une voie accessible.", "La suppression ne doit pas sanctionner des conclusions gênantes. Une évaluation indépendante et contradictoire doit établir l'échec du dispositif. Réviser le délai si quatre ans empêchent de voir les résultats ou maintiennent trop longtemps une participation décorative."),
16: ("Tester une enveloppe comprise entre 1 % et 3 % des dépenses annuelles d'investissement effectivement arbitrables du territoire, après obligations légales et continuité des services. Publier aussi sa part du budget total pour éviter une présentation trompeuse. Financer l'accompagnement et l'entretien des projets, avec correction des écarts entre quartiers.", "Cette assiette précise la fourchette déjà proposée ; elle n'est pas un optimum démontré. Une part plus élevée attend des résultats sur l'inclusion, la réalisation et les coûts complets. Revoir l'enveloppe si elle prive le socle de moyens ou reste trop faible pour permettre des choix réels."),
17: ("Retenir cinq ans par défaut, avec renouvellement d'un cinquième du collège chaque année et absence de renouvellement immédiat. Une durée de quatre ou six ans reste possible par justification publique liée au domaine, auditée avant nomination. Les archives et équipes d'appui assurent la continuité ; une évaluation intermédiaire porte sur les méthodes et obligations.", "Une durée uniforme simplifie la règle mais ne convient pas nécessairement à toutes les recherches. Réviser si la rotation détruit la mémoire ou si les mêmes réseaux gardent le contrôle. Une conclusion impopulaire ne constitue jamais un motif de révocation."),
18: ("Évaluer un dossier de travaux et d'expérience, une mise en situation pertinente et la capacité à expliciter les limites du raisonnement, par un jury pluraliste tournant. Rendre les critères publics, limiter les frais et ouvrir un recours. Les voies non académiques sont recevables lorsque la fonction le permet ; les qualifications professionnelles légalement obligatoires demeurent applicables.", "Le diplôme seul écarterait des compétences utiles ; une nomination politique seule ne les établit pas. Vérifier diversité des parcours et qualité réelle du travail, sans certification des droits citoyens. Réviser les épreuves si elles mesurent surtout les moyens sociaux des candidats."),
19: ("Retenir une grille publique par responsabilité et temps de travail, adossée aux fonctions publiques comparables du territoire, avec plafond commun et aucune prime au résultat scientifique. Déclarer les intérêts pertinents ; interdire les avantages des acteurs concernés et imposer la récusation. Proposer deux ans de carence pour rejoindre un acteur directement affecté par les dossiers traités, avec contrôle indépendant et compensation proportionnée si nécessaire.", "Le montant exige des données salariales et budgétaires locales ; il sera fixé avant recrutement. Deux ans est une hypothèse révisable, pas une norme universelle. Réviser si le recrutement échoue, si les restrictions deviennent excessives ou si l'influence se déplace vers des intermédiaires."),
20: ("Attribuer chaque fonction au niveau le plus proche capable de garantir qualité, égalité d'accès et continuité. Organiser localement la délivrance des services ; mutualiser régionalement ou nationalement les réseaux, financements et stocks ; coordonner au niveau européen les dépendances partagées et mondialement les connaissances. Publier pour chaque fonction un responsable, un budget et un recours, avec financement compensant les inégalités territoriales.", "Ni proximité ni centralisation ne suffisent en elles-mêmes. Respecter les compétences constitutionnelles existantes jusqu'à leur éventuelle révision régulière. Revoir l'attribution lorsque les délais, coûts ou écarts d'accès augmentent."),
21: ("Commencer par un contrat public entre institutions : autorité responsable envers l'usager, contributeurs, financement, délais, contrôle et recours dans le droit applicable. Maintenir les niveaux apportant une compétence ou une proximité vérifiable. Proposer une fusion ciblée seulement si cette coordination échoue et si son évaluation démontre un bénéfice d'accès ou de responsabilité.", "Un guichet commun seul peut masquer la fragmentation ; une fusion générale peut détruire la proximité. Le contrat ne redistribue pas de lui-même les compétences légales. Réviser sur la base des résultats et du coût complet, y compris la transition et les garanties linguistiques ou territoriales."),
22: ("Retenir les actes et effets : coercition, discrimination, financement dissimulé, privilège institutionnel ou influence non traçable sur un dossier public. Une conviction exprimée librement, y compris religieuse ou critique du projet, n'est pas un motif de restriction. Appliquer les mêmes obligations fonctionnelles de transparence aux acteurs comparables, avec recours indépendant.", "Un statut spécial selon la doctrine ou une appréciation discrétionnaire de l'administration exposerait à la discrimination. Réviser les contrôles s'ils deviennent une surveillance des croyances ; ne collecter que les informations nécessaires à un conflit concret."),
}

p = ROOT / 'docs/20-questions-structurantes.md'
text = p.read_text(encoding='utf-8')
text = text.replace('version: "0.4"', 'version: "0.5"', 1)
text = text.replace("Il ne remplace pas les chapitres spécialisés. Il sert de synthèse : chaque réponse devra ensuite être testée, sourcée et précisée dans les documents concernés.", "Il rassemble les réponses de travail aux questions des chapitres, sans remplacer leurs développements. Les rubriques « Questions ouvertes » encore présentes dans ces chapitres sont à lire avec les réponses ci-dessous et la [carte de correspondance](#correspondance-avec-les-chapitres). Une réponse proposée n'est pas une validation empirique ni une règle juridique déjà applicable.")
text = text.replace('## Questionnaire d\'arbitrage institutionnel', "## Réponses d'arbitrage institutionnel")
text = text.replace("Les questions suivantes doivent aider à transformer les questions ouvertes en décisions de conception. Les options marquées « recommandée » constituent des **hypothèses de travail** cohérentes avec les décisions actuelles du projet ; elles ne sont ni des conclusions scientifiques ni des choix démocratiques déjà acquis.", "Les vingt-deux réponses suivantes retiennent une option argumentée au lieu de solliciter un choix du propriétaire. Elles constituent des **hypothèses de travail**, compatibles avec les décisions existantes, et non des conclusions scientifiques ou des décisions publiques déjà adoptées. Les délais et pourcentages proposés sont des paramètres d'essai à évaluer.")
pattern = re.compile(r"(#### (\d+)\. [^\n]+\n\n).*?(?=Sources pour éclairer le choix :)", re.S)
def answer_block(match):
    num = int(match[2])
    chosen, limit = answers[num]
    return match[1] + '**Réponse de travail.** ' + chosen + '\n\n**Alternative, limites et révision.** ' + limit + '\n\n'
text, replaced = pattern.subn(answer_block, text)
assert replaced == 22, replaced
text = text[:text.index('## Utilisation des réponses')] + (ROOT / '.responses-addendum.md').read_text(encoding='utf-8')
p.write_text(text, encoding='utf-8', newline='\n')
